Cleanup, much better inline docs, tests use public executable

diff --git a/pub-crypt b/pub-crypt
--- a/pub-crypt
+++ b/pub-crypt
@@ -1,17 +1,3 @@
-# read -r -d '' usage <<-'EOF'
-# Usage: pub-crypt [-e or -d] [file]
-#
-# Options:
-#   -e encrypt
-#   -d decrypt
-#
-# Examples:
-#   pub-crypt -e foo.txt > foo.txt.pub-crypt
-#   pub-crypt -d foo.txt.pub-crypt
-#   cat foo.txt | pub-crypt -e > foo.txt.pub-crypt
-#   cat foo.txt.pub-crypt > pub-crypt -d
-# EOF
-
 usage=`cat <<EOF
 Usage: pub-crypt [-e or -d] [file]
 
@@ -28,16 +14,16 @@ EOF
 `
 
 action=$1
-filename=$2
+fd=${2:-/dev/stdin}
 
-# filename=${2:-/dev/stdin} # todo (I think), go back to this version. Don't
-# make ./decrypt care about stdin vs file
+test -r $fd ||
+  { echo "error: can't read from $fd (does it exist?)" >&2 ; exit 1; }
 
 if [ $action ] ; then
-  if   [ $action = '-e' ] ; then ./encrypt.sh $filename
-  elif [ $action = '-d' ] ; then ./decrypt.sh $filename
-  else echo "$usage"
+  if   [ $action = '-e' ] ; then cat $fd | ./encrypt.sh
+  elif [ $action = '-d' ] ; then cat $fd | ./decrypt.sh
+  else echo "$usage" >&2; exit 1
   fi
 else
-  echo "$usage"
+  echo "$usage" >&2
 fi
